# site settings
title: Forty
subtitle: by HTML5 UP
email: andrewpalet@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 350 Las Colinas Blvd E.
city: Dallas
state: TX
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/AndrewPalet
gitlab_url:
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-palet-067a87130/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewpalet

# build settings
markdown: kramdown

sass:
  style: compressed
